"""GridLAB-D Pandas Module

Players
-------

Players are used to read CSV files into memory and synchronize the columns to
properties of the player's parent object. By default the first column is the
timestamps of the data rows to synchronize.

The following properties are supported by players.

- `property`: a comma-delimited list of property names to read from the CSV
  file. If `property` is omitted, the CSV file must contain a header line to
  indicate which properties are to be read in. 

- `file`: the pathname of the CSV file to read.

- `timezone`: the timezone of the timestamps if not specified in the
  data file's `timestamp` column.

- `options`: JSON text of options overrides for `pandas.read_csv()`. The
  default `options` depends on whether `property` is specified.

| Options | `property` set | no `property` |
| ------- | -------------- | ------------- |
| `header` | `None` | `0` |
| `parse_dates` | `["timestamp"]` | `True` |
| `usecols` | `"timestamp"]+properties` | `None` |
| `names` | `["timestamp"]+properties` | `None` |
| `converters` | `{x:str for x in properties}` | `None` |
| `dtype` | `None` | `str `|

The following examples illustrate how to use players. The GLM class `example`
is defined as follows.

    class test
    {
        double x[s];
        double y[m];
    }

where the terms in square brackets after the property names are their
units, i.e., seconds and meters, respectively. If values are provided
with different units, then the data will be automatically converted to
units specified by the class.

*Simple player*:

In this example, the file `test_player.csv` contains this data.

    timestamp,x,y
    2000-01-01 00:00:00,60,0
    2000-01-01 01:00:00,61,1
    2000-01-01 02:00:00,62,2
    2000-01-01 04:00:00,64,3
    2000-01-01 05:00:00,65,4
    2000-01-01 10:00:00,64,5
    2000-01-01 11:00:00,63,6
    2000-01-01 12:00:00,62,7
    2000-01-01 13:00:00,61,8
    2000-01-01 14:00:00,60,9


Use the following to update the properties `x` and `y` in an object of class
`test` from data in the file `test_player.csv`.

    object example
    {
        object player
        {
            file "test_player.csv";
        };
    }

*Player missing timezones*:

If you need to specify the timezone for the timestamp use the following.

    object example
    {
        object player
        {
            file "test_player.csv";
            timezone "America/Los_Angeles";
        };
    }

Note that only timezones supported by Python `zoneinfo` module are supported.

*Player missing header row*:

The next example illustrates how to read data from the same CSV file when it
has no header to provide the property names.

    object example
    {
        object player
        {
            file "test_player.csv";
            options "{'header':None,'names':['timestamp','x','y']}";
            property "x,y";
        };
    }

Recorders
---------

Recorders are used to write CSV files from memory when objects are synchronize
from properties of the recorder's parent object. By default the first column
is the timestamp of the data rows generated by synchronization events.

The following properties are supported by recorders.

- `property`: a comma-delimited list of property names to write to the
  CSV file.

- `file`: the name of the CSV file to write. Any file format supported
  by `pandas.read_csv()` is supported, include compressed CSV files, e.g.,
  using `gzip`.

- `interval[s]`: the interval at which to sample the properties. If
  `0` (the default) is specified, then the properties are sampled at every
  iteration. If `-1` is specified, then the properties are sampled only when
  one of the values changes.

- `timezone`: the timezone of the timestamps to write the data file.
  The default timezone is UTC.

- `dtformat`: the date/time format to use when writing timestamps.

- `units`: specifies whether and how units information is include. The
  default is `None`, which does not include any units information in the
  output. If `INLINE` is specified, the units are included with the value
  is each cell. If `HEADER` is specified, the units are included as part
  of the column names, e.g., `name[unit]`.

- `flush`: specifies whether the output buffer is flushed with each write.


The following examples illustrate how to use a recorder for the same GLM class
used in the player examples.

*Simple recorder*:

This example records the properties to columns of the CSV file.

    object recorder
    {
        file "test_recorder.csv";
        property "x,y";
    }

*Recorder timezone*:

To specify the timezone of the `timestamp` column include the `timezone`
property.

    object recorder
    {
        file "test_recorder.csv";
        property "x,y";
        timezone "America/Los_Angeles";
    };

*Recorders timestamp format*:

To specify the date/time format fof the timestaom include the `dtformat`
property.

    object recorder
    {
        file "test_recorder.csv";
        property "x,y";
        timezone "America/Los_Angeles";
        dtformat "%Y-%m-%d %H:%M:%S %Z";
    };
"""

import os
import sys
import math
from datetime import datetime, timezone
from zoneinfo import ZoneInfo
from datetime import datetime, timezone
import re

import pandas as pd

from glm_utilities import MutableData, name_unit, value_unit
from glm_timestamp import TIMESTAMP

recorder:dict = None
"""Active recorder objects in GridLAB-D"""

player:dict = None
"""Active player objects in GridLAB-D"""

#
# GLOBAL EVENT HANDLERS
#

def on_init(t:int) -> int:
    """Pandas module initialization

    Arguments
    ---------
    - `t`: initialization timestamp

    Returns
    -------
    - `int`: `gldcore.INIT_FAILED` on failure, `gldcore.INIT_OK` on success,
      `gldcore.INIT_DEFER` on defer initialization
    """
    global recorder
    recorder = {}

    global player
    player = {}

    return gldcore.INIT_OK

def on_term(t:int):
    """Terminate all players

    Arguments
    ---------
    - `t`: termination timestamp
    """
    for this in recorder.values():
        this.file.close()

    return None

#
# RECORDER CLASS EVENT HANDLERS
#

def recorder_init(obj:str,t:int) -> int:
    """Initialize a recorder

    Arguments
    ---------
    - `obj`: object name
    - `t`: initial timestamp

    Returns
    -------
    - `int`: 0 on success, non-zero on failure
    """
    parent = gldcore.get_value(obj,"parent")
    properties = gldcore.get_value(obj,"property").split(",")
    file = gldcore.get_value(obj,"file")
    assert file != "", f"{obj=} {file=} is not valid"
    file = open(file,"w")
    interval = int(gldcore.get_value(obj,"interval").split()[0])
    if interval > 0:
        gldcore.set_value(obj,"heartbeat",f"{interval:.0f}")
    timezone = gldcore.get_value(obj,"timezone")
    dtformat = gldcore.get_value(obj,"dtformat")
    flush = gldcore.get_value(obj,"flush")
    source = {}
    units = gldcore.get_value(obj,"units")
    for prop in properties:
        try:
            source[prop] = gldcore.property(parent,prop)
        except Exception as err:
            e_type, e_value, _ = sys.exc_info()
            raise e_type(f"{obj}.properties: '{prop}' {e_value}") from err

    this = {
        "file": file,
        "interval": interval,
        "parent": parent,
        "source": source,
        "last": None,
        "timezone": ZoneInfo(timezone) if timezone else None,
        "dtformat": dtformat if dtformat else None,
        "flush": flush,
        "units": units,
    }
    recorder[obj] = MutableData(**this)

    header = ["timestamp"]
    if units != "HEADER":
        header.extend(properties)
    else:
        pclass = gldcore.get_class(gldcore.get_object(parent)["class"])
        for name in properties:
            try:
                unit = pclass[name]["unit"]
            except:
                unit = None
            header.append(f"{name}[{unit}]" if unit else name)
    file.write(",".join(header)+"\n")


    return gldcore.INIT_OK

def recorder_commit(obj:str,t:int) -> int:
    """Update a recorder

    Arguments
    ---------
    - `obj`: object name
    - `t`: current timestamp

    Returns
    -------
    - `int`: next timestamp
    """
    this = recorder[obj]
    if this.interval <= 0 or t % this.interval == 0: # time to sample values
        row = []
        for var,prop in this.source.items():
            value = str(prop)
            if this.units != "INLINE":
                value,_ = value_unit(value)
            value = str(value)
            row.append(f'"{value}"' if ',' in value else value)
        if this.interval >= 0 or row != this.last:
            this.last = list(row)
            ts = datetime.fromtimestamp(t,tz=this.timezone if this.timezone else timezone.utc)
            fmt = this.dtformat
            row.insert(0,ts.strftime(fmt) if fmt else ts.isoformat())
            this.file.write(",".join(row)+"\n")
            if this.flush:
                this.file.flush()
    return ( t // this.interval + 1 ) * this.interval \
        if this.interval > 0 \
        else gldcore.NEVER

#
# PLAYER
#

def player_init(obj,t):
    """Initialize a player

    Arguments
    ---------
    - `obj`: object name
    - `t`: initial timestamp

    Returns
    -------
    - `int`: 0 on success, non-zero on failure
    """

    # get player info
    parent = gldcore.get_value(obj,"parent")

    properties = [x.strip() for x in gldcore.get_value(obj,"property").split(",") if x != ""]

    options = eval(gldcore.get_value(obj,"options"))
    options = options if options else {}

    def set_defaults(data,**kwargs):
        for key,value in kwargs.items():
            if not key in data:
                data[key] = value
        return data

    set_defaults(options,
        header="infer" if properties else 0,
        parse_dates=["timestamp"] if properties else True,
        usecols=["timestamp"]+properties if properties else None,
        converters={x:str for x in properties} if properties else None,
        dtype=None if properties else str,
        )

    file = gldcore.get_value(obj,"file")
    data = pd.read_csv(file,**options)

    if not properties:
        properties = data.columns[1:].tolist()
    assert properties, f"{obj=} no properties specified"

    source = {}
    unit = {}
    for prop in properties:
        try:
            name,unit[prop] = name_unit(prop)
            source[prop] = gldcore.property(parent,name)
        except Exception as err:
            e_type, e_value, _ = sys.exc_info()
            raise e_type(f"{obj}.properties: '{prop}' {e_value}") from err

    try:
        timezone = gldcore.get_value(obj,"timezone")
        data.timestamp = pd.DatetimeIndex(data.timestamp).tz_localize(timezone if timezone else "UTC")
    except:
        data.timestamp = pd.DatetimeIndex(data.timestamp).tz_convert("UTC")

    # setup player
    this = {
        "data": data,
        "row": 0,
        "source": source,
        "unit": unit,
        "timestamp": None
        }
    player[obj] = MutableData(**this)

    return gldcore.INIT_OK

def player_precommit(obj,t):
    """Update a player

    Arguments
    ---------

    - `obj`: object name
    - `t`: current timestamp

    Returns
    -------

    - `int`: next timestamp
    """
    this = player[obj]
    try:
        data = this.data.loc[this.row]
    except KeyError:
        return gldcore.NEVER

    this.timestamp = TIMESTAMP(int(data.timestamp.timestamp()))

    # update time was missed
    if this.timestamp < t:
        gldcore.warning(f"missed timestamp {this.timestamp}>")

    # update time is in the future
    if this.timestamp > t:
        return this.timestamp

    # update time has arrived
    for src,prop in this.source.items():
        if this.unit[src] is None:
            value = str(data[src])
        else:
            value = f"{data[src]} {this.unit[src]}"
        prop.set_value(value)

    # move to next row
    this.row += 1
    try:
        tnext = int(this.data.loc[this.row,"timestamp"].timestamp())
        return -tnext
    except KeyError:
        return gldcore.NEVER
