#!/bin/bash
## Syntax: gridlabd docs [OPTIONS ...]
##
## Options:
##
## * `-b|--branch BRANCH`: open docs from github branch BRANCH
##
## * `-d|--document NAME`: open document NAME (must include full path)
##
## * `-h|--help|help`: output this help
##
## * `-f|--folder DIR`: open folder DIR (must include root /)
##
## * `-o|--organization ORG`: open docs from github owner ORG
##
## * `--page`: open docs in page-only layout (no sidebar index)
##
## Opens the document browser at the indicated folder and document
## on the specified branch of the organization's `gridlabd` project.
## The default organization is `arras-energy`, the default branch is
## `master`, the default folder is `/`, and the default document is
## `README.md`.
##
## Exit codes:
##
## * `0`: ok
##
## * `1`: invalid option
##
## Caveat:
##
## If you do not specify the folder and document, the documentation browser
## will reopen the previous document, if any was viewed recently. The default
## folder and document will only be opened on the first view in 24 hours.
##
## See also:
##
## * https://docs.arras.energy/
##

ORG=$($GLD_BIN/gridlabd.bin --version=origin | cut -f4 -d/)
BRA=$($GLD_BIN/gridlabd.bin --version=git-branch)
DIR=/
DOC=/README.md
EXE=$0

E_OK=0
E_SYNTAX=1
PAGE="index"

while [ $# -gt 0 ]; do
    case $1 in
    --organization|-o)
        ORG=$2
        shift
        ;;
    --branch|-b)
        BRA=$2
        shift
        ;;
    --folder|-f)
        DIR=$2
        shift
        ;;
    --help|-h|help)
        grep '^## ' $EXE | cut -c4- | sed 's/`//g'
        exit $E_OK
        ;;
    --document|-d)
        DOC=$2
        shift
        ;;
    --page)
        PAGE="_page"
        ;;
    *)
        echo "ERROR: option '$1' is invalid"
        exit $E_SYNTAX
        ;;
    esac
    shift
done

open 'https://docs.arras.energy/'${PAGE}'.html?owner='${ORG:-arras.energy}'&project=gridlabd&branch='${BRA:-master}'&folder='$DIR'&doc='$DOC
