#!/bin/bash
## Syntax: source [--copy DIR|FILE]
## 
## Read source file from repository
## 
## EXIT 0 - ok
## EXIT 1 - not found
## EXIT 2 - syntax error
## EXIT 3 - missing folder
## EXIT 4 - folder exists
## 

if [ $# -eq 0 ]; then
    grep '^## Syntax: ' $0 | cut -c4-
    exit 2
fi

ORIGIN=$(gridlabd.bin --version=origin)
COMMIT=$(gridlabd.bin --version=commit)
SRCPATH=/usr/local/src
SRCDIR=gridlabd

if [ $1 == "--copy" ]; then
    if [ $# -eq 2 ]; then
        SRCPATH=$(dirname $2)
        SRCDIR=$(basename $2)
    fi
    if [ -d "$SRCPATH" ]; then
        cd $SRCPATH
        if [ -d "$SRCDIR" ]; then
            echo "ERROR [source]: '$SRCDIR' exists"
            exit 4
        fi
        git clone $ORIGIN $(basename $2) 
        cd $SRCDIR
        git reset --hard $COMMIT
    else
        echo "ERROR [source]: '$SRCPATH' does not exist"
        exit 3
    fi
else
    SOURCE=${ORIGIN/github.com/raw.githubusercontent.com}/$COMMIT/$1
    CODE=$(curl --retry 5 -sfLI $SOURCE | head -n 1 | cut -f2 -d' ')
    if [ $? -ne 0 -o $CODE -ne 200 ]; then
        echo "ERROR [source]: $1 -> $CODE"
        exit 1
    else
        curl --retry 5 -sL $SOURCE
    fi
fi

exit 0
