#!/bin/bash
## Syntax: gridlabd marimo NAME
## 
## Run marimo in gridlabd environment.
## 

if [ $# -eq 0 ]; then
    grep '^## ' $0 | cut -c4-
    exit 0
fi

DIR=$GLD_ETC/marimo
EXE=$DIR/$1.py
if [ ! -d $DIR ]; then
    mkdir $DIR
fi

if [ ! -f $EXE ]; then
    SOURCE=$($GLD_BIN/gridlabd.bin --version=origin | cut -f4- -d/)
    curl -sL https://raw.githubusercontent.com/arras-energy/marimo/refs/heads/main/source/$1.py > $EXE
    if [ $? -ne 0 ]; then
        rm -f $EXE
        echo "$1 not found"
        exit 1
    fi
fi

marimo run $EXE
