name: analysis

on:
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  
  pylint:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@main

    - name: Setup python
      uses: actions/setup-python@main
      with:
        python-version: '3.12'

    - name: Install pylint
      run: python3 -m pip install --upgrade pip pylint
      
    - name: Analyse python
      run:  python3 -m pylint python/*.py || true

    - name: Analyse runtime
      run:  python3 -m pylint runtime/*.py || true

    - name: Analyse subcommands
      run:  python3 -m pylint subcommands/gridlabd-*.py || true

  cppcheck:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@main

    - name: Setup python
      uses: actions/setup-python@main
      with:
        python-version: '3.12'

    - name: Install cppcheck
      run: sudo apt-get install cppcheck
      
    - name: Analyse source C/C++
      run: cppcheck -j $(nproc) --library=std source/*.{c,cpp} || true
