name: develop-push-dockerhub

on:
  push:
    branches: [ develop ]

jobs:
  buildUbuntuDockerhub:

    runs-on: ubuntu-24.04
    environment: Integration
#    needs: buildUbuntu24FastS3
# will need to replace job dependency to workflow dependency when new ami's generated again
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run CF invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CF_ID }} --paths '/*'

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/packer/Dockerfile.dev.ul
        push: true
        tags: lfenergy/arras:develop
