name: develop-website-sync

on:
  push:
    branches: [ develop ]

jobs:
  updateS3websites:
    runs-on: ubuntu-24.04
    environment: Integration

    steps:
    - uses: actions/checkout@v4

      # this is to fix GIT not liking owner of the checkout dir
    - name: Set ownership
      run: |
        chown -R $(id -u):$(id -g) $PWD

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Website s3 sync
      run: |
        aws s3 sync ./cloud/websites/code.arras.energy/ s3://code-dev.arras.energy --acl public-read
        aws s3 sync ./cloud/websites/docs.arras.energy/ s3://docs-dev.arras.energy --acl public-read
        aws s3 sync ./cloud/websites/geodata.arras.energy/ s3://geodata-dev.arras.energy --acl public-read
        aws s3 sync ./cloud/websites/install.arras.energy/ s3://install-dev.arras.energy --acl public-read
        aws s3 sync ./cloud/websites/status.arras.energy/ s3://status-dev.arras.energy --acl public-read
        aws s3 sync ./cloud/websites/tutorials.arras.energy/ s3://tutorials-dev.arras.energy --acl public-read
        aws s3 sync ./cloud/websites/www.arras.energy/ s3://www-dev.arras.energy --acl public-read
# re-enable when buckets live and cloudfront added
#    - name: Run CF invalidation
#      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DEV_CF_ID }} --paths '/*'
