name: master-dockerhub

on:
  push:
    branches: [ master ]

jobs:
  buildUbuntuDockerhub:

    runs-on: ubuntu-24.04
    environment: Integration
#    needs: buildUbuntu24FastS3
# disabled dependency until reinstating fast install amis

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
# Change to OIDC and re-enable once image generation is confirmed working on arras
#    - name: Configure AWS Credentials
#      uses: aws-actions/configure-aws-credentials@v2
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_REGION }}

#    - name: Run CF invalidation
#      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CF_ID }} --paths '/*'

    - name: Set output
      run: |
        echo "VERSION=$(./build-aux/version.sh --version)" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/packer/Dockerfile.prod.ul
        push: true
        tags: lfenergy/arras:latest, lfenergy/arras:${{ env.VERSION }}
